os: Visual Studio 2015

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0


build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release

before_test:
  - ps: Start-FileDownload 'http://download.microsoft.com/download/f/2/6/f263ac46-1fe9-4ae9-8fd3-21102100ebf5/msxsl.exe'
  - cmd: dir
  
test_script:
  - cmd: ctest -VV -C Release --no-compress-output -T test
  - ps: Copy-Item Testing\$(Get-Content Testing\TAG -TotalCount 1)\Test.xml ctestTestResult.xml
  - cmd: msxsl.exe ctestTestResult.xml ../tools/ctest-to-junit.xsl -o junitTestResult.xml
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junitTestResult.xml))
